name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: monergerges2
          outputs: dist/snake-dark.svg?palette=github-dark
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Commit and Push
        run: |
          git add dist/snake-dark.svg
          git commit -m "Update dark snake animation" || echo "No changes to commit"
          git push origin HEAD:output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}